clearning/urls.py
from django.contrib import admin

from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('modules.main.urls')),
    path('plans/', include('modules.plans.urls')),
    path('courses/', include('modules.courses.urls')),
    path('enrollments/', include('modules.enrollments.urls')),
    path('students/', include('modules.students.urls')),
    path('teachers/', include('modules.teachers.urls')),]

users/urls.py
from django.urls import path

from . import views


app_name = 'users'

urlpatterns = [
	path('login', views.LoginView.as_view(), name='login'),
	path('logout', views.LogoutView.as_view(), name='logout'),
	path('register', views.AccountRegisterView.as_view(), name='register'),
	path('forgot-password', views.ForgotPasswordView.as_view(), name='forgot-password'),
	path('teacher/register', views.TeacherRegisterView.as_view(), name='teacher-register'),
	path('', views.AccountsView.as_view(), name='list'),
]

users/models.py
from json import dumps, loads
from uuid import uuid4

from django.contrib.auth.models import AbstractUser, User
from django.db import models

from modules.core.models import BaseModel
from modules.plans.models import Plan


class UserAccount(AbstractUser):
	
	ADMIN = 1
	SUBSCRIPTION = 2
	TEACHER	= 3
	STUDENT = 4

	USER_TYPE_CHOICES = [
		(ADMIN, 'ADMINISTRADOR'),
		(SUBSCRIPTION, 'SUBSCRIPTION'),
		(TEACHER, 'PROFESOR'),
		(STUDENT, 'ALUMNO'),
	]

	user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES,
												 default=USER_TYPE_CHOICES[1][0])

	verified = models.BooleanField(default=False)
	subscriptions = models.ManyToManyField(Plan, through='AccountSubscriptions')


	def __str__(self):
		return "{nombre}, {apellido} [{tipo}]".format(
			nombre=self.first_name,
			apellido=self.last_name,
			tipo=self.get_user_type_display()
		)

	@property
	def full_name(self):
		return f"{self.first_name} {self.last_name}"

	def to_json(self, subscriptions=False):
		as_json = {}
		as_json['id'] = str(self.id)
		as_json['first_name'] = self.first_name
		as_json['last_name'] = self.last_name
		as_json['user_type'] = self.user_type
		as_json['user_type_display'] = self.get_user_type_display()
		as_json['verified'] = self.verified

		if subscriptions:
			as_json['subscriptions'] = []

			for s in self.subscriptions.all():
				as_json['subscriptions'].append(loads(s.to_json()))

		return dumps(as_json)


class AccountSubscriptions(BaseModel):

	status_choices = [
		('A', 'ACTIVE'),
		('I', 'INACTIVE'),
	]

	id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
	account = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
	plan = models.ForeignKey(Plan, on_delete=models.CASCADE)

	status = models.CharField(
		max_length=8,
		choices=status_choices,
		default=status_choices[0][0]
	)

	def __str__(self):
		return "{_id}, {account}, {plan}".format(
			_id=self.id,
			account=str(self.account),
			plan=str(self.plan)
		)

	def to_json(self):
		as_json = {}
		as_json['id'] = str(self.id)
		as_json['account'] = loads(self.account.to_json())
		as_json['plan'] = loads(self.plan.to_json())
		as_json['status'] = self.status

		return dumps(as_json)

users/forms.py
from django import forms


class LoginForm(forms.Form):
	username = forms.CharField(label="Nombre de usuario", required=True)
	password = forms.CharField(label="Contraseña", required=True)


class AccountRegisterForm(forms.Form):
	first_name = forms.CharField(max_length=64)
	last_name = forms.CharField(max_length=64)
	email = forms.CharField(max_length=128)
	username = forms.CharField(max_length=128)
	password = forms.CharField(max_length=128)
	password_confirm = forms.CharField(max_length=128)


class ForgotPasswordForm(forms.Form):
	username = forms.CharField(max_length=128)
	password = forms.CharField(max_length=128)
	password_confirm = forms.CharField(max_length=128)

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.utils.decorators import method_decorator

from .forms import LoginForm, AccountRegisterForm, ForgotPasswordForm
from .models import UserAccount
from modules.plans.models import Plan


class LoginView(View):

	template_name = 'users/login.html'
	form = LoginForm

	def get(self, request):
		context = {}
		context['status'] = 100

		if str(request.user) != "AnonymousUser":
			return redirect(reverse('main:home'))

		return render(request, self.template_name, context)

	def post(self, request):
		context = {}
		form_data = self.form(request.POST)

		if form_data.is_valid():
			username = form_data.cleaned_data['username']
			password = form_data.cleaned_data['password']
			logged_user = authenticate(username=username, password=password)

			if logged_user is not None:
				login(request, logged_user)
				context['status'] = 200
				context['message'] = 'Autenticación exitosa'
				return redirect(reverse('main:home'))
			else:
				context['status'] = 400
				context['message'] = 'Credenciales invalidas'
				return render(request, self.template_name, context)
		else:
			context['status'] = 400
			context['message'] = "Datos ingresados invalidos"

		return render(request, self.template_name, context)


class LogoutView(View):

	def get(self, request):
		logout(request)
		return redirect(reverse('users:login'))


@method_decorator([login_required], name='dispatch')
class TeacherRegisterView(View):

	form = AccountRegisterForm
	model = UserAccount
	template_name = 'users/register.html'

	def get(self, request):
		context = {}
		context['user_type'] = User.TEACHER

		return render(request, self.template_name, context)


	def post(self, request):
		context = {}
		form_data = self.form(request.POST)

		if form_data.is_valid():
			try:
				teacher = UserAccount(**form_data.cleaned_data)
				teacher.password = make_password(teacher.password)
				teacher.save()
			except Exception as e:
				print(f"E: {e}")
				pass

		return self.get(request, context)


class AccountRegisterView(View):

	form = AccountRegisterForm
	model = UserAccount
	template_name = 'users/register.html'

	def get(self, request):
		context = {}
		context['status'] = 100
		
		if str(request.user) != "AnonymousUser":
			return redirect(reverse('main:home'))

		return render(request, self.template_name, context)

	def post(self, request):
		context = {}
		form_data = self.form(request.POST)

		if form_data.is_valid():
			email = form_data.cleaned_data['email']
			username = form_data.cleaned_data['username']
			user_account = UserAccount.objects.filter(email=email, username=username).first()
			
			if user_account:
				context['status'] = 400
				context['message'] = "Ya existe una cuenta registrada con este email/username"
			else:
				password = form_data.cleaned_data['password']
				password_confirm = form_data.cleaned_data['password_confirm']

				if not password == password_confirm:
					context['status'] = 400
					context['message'] = "Las contraseñas ingresadas no coinciden"
				else:
					account = UserAccount()
					account.email = email
					account.username = username
					account.first_name = form_data.cleaned_data['first_name']
					account.last_name = form_data.cleaned_data['last_name']
					account.password = make_password(password)
					account.user_type = UserAccount.SUBSCRIPTION
					account.save()

					# Setear plan FREE por defecto
					plan = Plan.objects.filter(name='FREE').first()
					if not plan:
						plan = Plan(name='FREE')
						plan.save()
						plan.reload()
						
					account.subscriptions.add(plan)

					context['status'] = 201
					context['message'] = "Registro exitoso, inicie sesión para continuar"

					return render(request, LoginView.template_name, context)

		else:
			context['status'] = 400
			context['message'] = "Revisa los datos ingresados e intentalo nuevamente"

		return render(request, self.template_name, context)


class ForgotPasswordView(View):

	template_name = 'users/forgot-password.html'
	form = ForgotPasswordForm

	def get(self, request):
		context = {}
		return render(request, self.template_name, context)

	def post(self, request):
		context = {}

		try:
			form = self.form(request.POST)

			if form.is_valid():
				form = form.cleaned_data
				username = form['username']
				password = form['password']
				password_confirm = form['password_confirm']

				user = UserAccount.objects.get(username=username)

				if password == password_confirm:
					user.password = make_password(password)
					user.save()

					context['status'] = 200
					context['message'] = "La contraseña ha sido actualizada"

				else:
					context['status'] = 400
					context['message'] = "Las contraseñas ingresadas no son iguales"

			else:
				context['status'] = 400
				context['message'] = "Revise los datos ingresados e intentelo nuevamente"

		except ObjectDoesNotExist:
			context['status'] = 404
			context['message'] = "No existe un usuario con ese correo"

		except Exception as e:
			context['status'] = 500
			context['message'] = f"Error interno del servidor"

		return render(request, self.template_name, context)


class AccountsView(LoginRequiredMixin, View):

	template_name = "users/index.html"


	def get(self, request):
		context = {}
		account = request.user

		try:
			users = UserAccount.objects.filter()
			context['users'] = users
			context['message'] = "Todos los usuarios"
		except:
			context['users'] = []
			context['message'] = "Error"

		return render(request, self.template_name, context)

templates/users/forgot-password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>CLearning Forgot Password</title>

        <!-- Custom fonts for this template-->
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    </head>

    <body class="bg-gradient-primary">

        <div class="container">

            <!-- Outer Row -->
            <div class="row justify-content-center">

                <div class="col-xl-10 col-lg-12 col-md-9">

                    <div class="card o-hidden border-0 shadow-lg my-5">
                        <div class="card-body p-0">
                            <!-- Nested Row within Card Body -->
                            <div class="row">
                                <div class="col-lg-6 d-none d-lg-block bg-login-image">
                                    <img src="" />
                                </div>
                                <div class="col-lg-6">
                                    <div class="p-5">
                                        <div class="text-center">
                                            <h1 class="h4 text-gray-900 mb-4">Recuperar contraseña</h1>
                                        </div>
                                        <form class="user" method="post" action="{% url 'users:forgot-password' %}">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" class="form-control form-control-user" id="username"
                                                placeholder="Nombre de usuario o correo electronico" name="username">
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-6 mb-3 mb-sm-0">
                                                    <input type="password" class="form-control form-control-user"
                                                        id="password" placeholder="Contraseña" name="password">
                                                </div>
                                                <div class="col-sm-6">
                                                    <input type="password" class="form-control form-control-user"
                                                        id="password_confirm" placeholder="Repetir contraseña" name="password_confirm">
                                                </div>
                                            </div>

                                            {% if status == 400 %}
                                            
                                            <div class="alert alert-danger alert-dismissible show fade small">
                                                <div class="alert-body">
                                                    <button class="close" data-dismiss="alert"><span>×</span></button>
                                                    {{ message }}
                                                </div>
                                            </div>

                                            {% elif status == 200 or status == 201 %}

                                            <div class="alert alert-success alert-dismissible show fade small">
                                                <div class="alert-body small">
                                                    <button class="close" data-dismiss="alert"><span>×</span></button>
                                                    {{ message }}
                                                </div>
                                            </div>

                                            {% endif %}

                                            <input type="submit" class="btn btn-primary btn-user btn-block" value="Cambiar contraseña">
                                        </form>
                                        <hr>
                                        <div class="text-center">
                                            <a class="small" href="{% url 'users:register' %}">No tienes una cuenta? Registrate</a>
                                        </div>
                                        <div class="text-center">
                                            <a class="small" href="{% url 'users:login' %}">Ya tienes una cuenta? Inicia sesión</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>

        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    </body>
</html>

templates/users/index.html
{% extends '../base.html' %}

{% load static %}

{% block title %}Inicio{% endblock %}

{% block pagetitle %}Usuarios{% endblock %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h5 class="h5 mb-0 text-gray-800">Todos los usuarios registrados</h5>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
	</div>
	<div class="card-body">
        <div class="tab-content">
	        <div class="tab-pane fade show active">
	        	<div class="table-responsive">
		            <table class="table table-bordered" id="users-table" width="100%" cellspacing="0">
		                <thead>
		                    <tr>
		                        <th>Nombre</th>
		                        <th>Apellido</th>
		                        <th>Correo</th>
		                        <th>Usuario</th>
		                        <th>Tipo de usuario</th>
		                        <th>Acciones</th>
		                    </tr>
		                </thead>
		                <tbody id="users-table-body">
		                	{% for user in users %}
		                		<tr id="table-row-{{ user.id }}">
		                			<td>{{ user.first_name }}</td>
		                			<td>{{ user.last_name }}</td>
		                			<td>{{ user.email }}</td>
		                			<td>{{ user.username }}</td>
		                			<td>{{ user.get_user_type_display }}</td>
		                			<td><a href="#" class="danger" onclick="">Eliminar</a></td>
		                		</tr>
		                	{% endfor %}
		                </tbody>
		            </table>
	        	</div>
	        </div>
    	</div>
	</div>
</div>
{% endblock %}

{% block additionaljs %}
{% csrf_token %}
<script type="text/javascript" charset="utf-8" async defer>

	function getCookie(name) {
	    let cookieValue = null;
	    if (document.cookie && document.cookie !== '') {
	        const cookies = document.cookie.split(';');
	        for (let i = 0; i < cookies.length; i++) {
	            const cookie = cookies[i].trim();
	            // Does this cookie string begin with the name we want?
	            if (cookie.substring(0, name.length + 1) === (name + '=')) {
	                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
	                break;
	            }
	        }
	    }
	    return cookieValue;
	}

	$(document).ready(function(){
		$('#users-table').DataTable();
	})
</script>
{% endblock %}

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>CLearning Login</title>

        <!-- Custom fonts for this template-->
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    </head>

    <body class="bg-gradient-primary">

        <div class="container">

            <!-- Outer Row -->
            <div class="row justify-content-center">

                <div class="col-xl-10 col-lg-12 col-md-9">

                    <div class="card o-hidden border-0 shadow-lg my-5">
                        <div class="card-body p-0">
                            <!-- Nested Row within Card Body -->
                            <div class="row">
                                <div class="col-lg-6 d-none d-lg-block bg-login-image">
                                    <img src="" />
                                </div>
                                <div class="col-lg-6">
                                    <div class="p-5">
                                        <div class="text-center">
                                            <h1 class="h4 text-gray-900 mb-4">Bienvenido de nuevo!</h1>
                                        </div>
                                        <form class="user" method="post" action="{% url 'users:login' %}">
                                            {% csrf_token %}
                                            <div class="form-group">
                                                <input type="text" class="form-control form-control-user" 
                                                    id="username" name="username" aria-describedby="Nombre de usuario"
                                                    placeholder="Escriba su nombre de usuario">
                                            </div>
                                            <div class="form-group">
                                                <input type="password" class="form-control form-control-user"
                                                    id="password" name="password" placeholder="Escriba su contraseña">
                                            </div>
                                            <div class="form-group">
                                                <div class="custom-control custom-checkbox small">
                                                    <input type="checkbox" class="custom-control-input" id="customCheck">
                                                    <label class="custom-control-label" for="customCheck">Recuerdame
                                                    </label>
                                                </div>
                                            </div>

                                            {% if status == 400 %}
                                            
                                            <div class="alert alert-danger alert-dismissible show fade small">
                                                <div class="alert-body">
                                                    <button class="close" data-dismiss="alert"><span>×</span></button>
                                                    {{ message }}
                                                </div>
                                            </div>

                                            {% elif status == 200 or status == 201 %}

                                            <div class="alert alert-success alert-dismissible show fade small">
                                                <div class="alert-body">
                                                    <button class="close" data-dismiss="alert"><span>×</span></button>
                                                    {{ message }}
                                                </div>
                                            </div>

                                            {% endif %}

                                            <input type="submit" class="btn btn-primary btn-user btn-block" value="Iniciar sesión">
                                        </form>
                                        <hr>
                                        <div class="text-center">
                                            <a class="small" href="{% url 'users:forgot-password' %}">Olvidaste tu contraseña?</a>
                                        </div>
                                        <div class="text-center">
                                            <a class="small" href="{% url 'users:register' %}">Crea una cuenta</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>

        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    </body>
</html>

templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>CLearning Login</title>

        <!-- Custom fonts for this template-->
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link
            href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
            rel="stylesheet">

        <!-- Custom styles for this template-->
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    </head>

    <body class="bg-gradient-primary">

        <div class="container">

            <!-- Outer Row -->
            <div class="row justify-content-center">

                <div class="col-xl-10 col-lg-12 col-md-9">

                    <div class="card o-hidden border-0 shadow-lg my-5">
                        <div class="card-body p-0">
                            <!-- Nested Row within Card Body -->
                            <div class="row">
                                <div class="col-lg-6 d-none d-lg-block bg-login-image">
                                    <img src="" />
                                </div>
                                <div class="col-lg-6">
                                    <div class="p-5">
                                        <div class="text-center">
                                            <h1 class="h4 text-gray-900 mb-4">Crea una cuenta</h1>
                                        </div>
                                        <form class="user" method="post" action="{% url 'users:register' %}">
                                            {% csrf_token %}
                                            <div class="form-group row">
                                                <div class="col-sm-6 mb-3 mb-sm-0">
                                                    <input type="text" class="form-control form-control-user" id="first_name"
                                                        placeholder="Primer nombre" name="first_name">
                                                </div>
                                                <div class="col-sm-6">
                                                    <input type="text" class="form-control form-control-user" id="last_name"
                                                        placeholder="Primer apellido" name="last_name">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <input type="email" class="form-control form-control-user" id="email"
                                                    placeholder="Correo electronico" name="email">
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control form-control-user" id="username"
                                                    placeholder="Nombre de usuario" name="username">
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-6 mb-3 mb-sm-0">
                                                    <input type="password" class="form-control form-control-user"
                                                        id="password" placeholder="Contraseña" name="password">
                                                </div>
                                                <div class="col-sm-6">
                                                    <input type="password" class="form-control form-control-user"
                                                        id="password_confirm" placeholder="Repetir contraseña" name="password_confirm">
                                                </div>
                                            </div>

                                            {% if status == 400 %}
                                            
                                            <div class="alert alert-danger alert-dismissible show fade small">
                                                <div class="alert-body">
                                                    <button class="close" data-dismiss="alert"><span>×</span></button>
                                                    {{ message }}
                                                </div>
                                            </div>

                                            {% elif status == 200 or status == 201 %}

                                            <div class="alert alert-success alert-dismissible show fade small">
                                                <div class="alert-body small">
                                                    <button class="close" data-dismiss="alert"><span>×</span></button>
                                                    {{ message }}
                                                </div>
                                            </div>

                                            {% endif %}

                                            <input type="submit" class="btn btn-primary btn-user btn-block" value="Registrar cuenta">
                                        </form>
                                        <hr>
                                        <div class="text-center">
                                            <a class="small" href="{% url 'users:forgot-password' %}">Olvidaste tu contraseña?</a>
                                        </div>
                                        <div class="text-center">
                                            <a class="small" href="{% url 'users:login' %}">Ya tienes una cuenta? Inicia sesión</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </div>

        </div>

        <!-- Bootstrap core JavaScript-->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

        <!-- Core plugin JavaScript-->
        <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

        <!-- Custom scripts for all pages-->
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    </body>
</html>